### ISSUE TITLE
Adopt standard Java project layout

### ISSUE THREAD

**Issue by abstratt** [williamfiset/Algorithms#120]
In the last 10 years, the convention for Java project [directory structure](https://www.baeldung.com/maven-directory-structure#directory-layout
) introduced my Maven became well accepted. Other tools understand it as well (including Gradle). If you follow it, your build configuration becomes quite simpler (in this project's case, would need no mention of source locations at all, which it has plenty now). Also, since this is such a popular educational resource, it would teach learners how to properly structure their own Java projects.

If there is interest in this, I'd be happy to submit a PR.

**Comment by williamfiset** [comment]
Hi Rafael, thanks for the suggestion. I like the idea of standardizing the structure of the repo if makes it can make it easier for others to contribute. Feel free to give this a go, otherwise I'm happy to do the changes in the near future.

If this ends up following through there are two other things I'll have to change that I'm documenting right here:
- Youtube description links
- The repo Wiki/README with instructions on how to get started

**Comment by abstratt** [comment]
Hi @williamfiset - I'd be happy to do this now, unless it is not the best time.

One thing I wanted to confirm is that usually the tests have a similar package structure as the code being tested (which also allows for tests to access package-private elements of the tested code, which otherwise may have to be made public just for the sake of being accessible to tests). Currently, the tests have javatests.com.williamfiset.algorithms as package prefix - I'd propose they used com.williamfiset.algorithms.geometry as a prefix instead, i.e., removing the javatests prefix.

The source tree for the code and tests would end up like this:

```
.
├───src
│   ├───main
│   │   └───java
│   │       └───com
│   │           └───williamfiset
│   │               └───algorithms 
│   │                   └───search
│   │                       └───InterpolationSearch.java
│   │                    ...
│   └───test
│       └───java
│   │       └───com
│   │           └───williamfiset
│   │               └───algorithms 
│   │                   └───search
│   │                       └───InterpolationSearchTest.java
```
Which is the typical layout for Maven/Gradle Java projects.

Are you fine with that?

**Comment by williamfiset** [comment]
Yes, that sgtm. Right now is a good time, the longer we wait the harder it will be to do this.

**Comment by abstratt** [comment]
Alright, I am on it! Will assign this issue to myself.

**Comment by abstratt** [comment]
Thanks for merging those changes promptly, @williamfiset !

I noticed that another PR, based on the original structure, was merged just before the restructuring, so the files added will need to be moved to the new structure in a new commit... I could do that if it helps. 

Also, I was hoping git would be smart enough not to be confused with the path relocations so existing PRs would not become invalid because of this change, but from looking at some open PRs, I guess I was wrong. :(

**Comment by abstratt** [comment]
Actually, I think if they pulled the new changes, git will be able to solve the conflicts automatically.

**Comment by williamfiset** [comment]
Ok, I will move those files later don't worry about it. I thought that you were moving the files so I merged those changes before, but you actually copied them from what I can see which is better.

Don't worry about the breaking PRs, most of them are old and aren't being looked at. Are there any more changes other than those I mentioned in https://github.com/williamfiset/Algorithms/issues/120#issuecomment-581156746? Otherwise I'll reassign to myself

**Comment by abstratt** [comment]
I am all done, feel free to assign to yourself, close etc.

**Comment by abstratt** [comment]
> File header instructions on how to run an individual test file in each 'examples' directory example

I think this one was taken care by the refactor tool in Eclipse.

**Comment by williamfiset** [comment]
Wonderful, thanks for the changes!
