### ISSUE TITLE
Add Tests For Sorting

### ISSUE THREAD

**Issue by nishantc1527** [williamfiset/Algorithms#180]
Right now the only testing class for sorting is in radix sort. Everything else is in the actual class itself in the main method.

**Comment by williamfiset** [comment]
Thanks for pointing this out. An example of how to execute the particular sorting method is nice, but the testing functionality certainly belongs in:

https://github.com/williamfiset/Algorithms/tree/master/src/test/java/com/williamfiset/algorithms/sorting

There's also a Main.java source file for Radix sort added by @EAlexa in the test folder, but I think we should move it to the RadixSort.java file as an example rather than keep it in the test folder:

https://github.com/williamfiset/Algorithms/blob/master/src/test/java/com/williamfiset/algorithms/sorting/Main.java

**Comment by williamfiset** [comment]
The build was breaking because apparently GitHub doesn't track case sensitive changes by default: https://stackoverflow.com/questions/17683458/how-do-i-commit-case-sensitive-only-filename-changes-in-git

Fixed using:

$ git mv -f src/main/java/com/williamfiset/algorithms/sorting/Mergesort.java src/main/java/com/williamfiset/algorithms/sorting/MergeSort.java
$ git mv -f src/main/java/com/williamfiset/algorithms/sorting/Quicksort.java src/main/java/com/williamfiset/algorithms/sorting/QuickSort.java
